FROM docker.io/ubuntu:20.04 as minimal

ENV DEBIAN_FRONTEND=noninteractive

ENV TUTOR_SKIP_BOOTSTRAP=y TUTOR_SKIP_SETUP=y

RUN apt-get update -y

RUN apt install python3-pip git -y

RUN apt-get install -y apt-transport-https ca-certificates curl software-properties-common && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - &&  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && apt-get update -y && apt-get install -y docker-ce docker-ce-cli containerd.io

RUN pip3 install tutor[full]==16.1.8

RUN tutor config save

RUN tutor images build openedx --build-arg EDX_PLATFORM_REPOSITORY=https://github.com/edcast/edx-platform --build-arg EDX_PLATFORM_VERSION=palm-release/migration-version
