FROM docker.io/ubuntu:20.04 as minimal

RUN apt-get update -y

RUN apt install python3-pip git -y

RUN pip3 install tutor[full]==16.1.8

ENV TUTOR_SKIP_BOOTSTRAP=y TUTOR_SKIP_SETUP=y

RUN tutor config save

RUN tutor images build openedx --build-arg EDX_PLATFORM_REPOSITORY=https://github.com/edcast/edx-platform --build-arg EDX_PLATFORM_VERSION=palm-release/migration-version
